name: NPM Audit Fix Run

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Specify a base branch"
        required: false
        default: "main"
      package_manager:
        description: "Specify package manager (npm or yarn)"
        required: false
        default: "yarn"
      script:
        description: "Specify the npm/yarn script to run if available"
        required: false
        type: string
        default: "yarn all"
      yarn_version:
        required: false
        type: string
        default: "3.6.3"

  schedule:
    - cron: "0 0 * * 1"

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/audit_fix.yml@v1
    with:
      base_branch: ${{ inputs.base_branch || 'main' }}
      package_manager: "yarn"
      script: ${{ inputs.script || 'yarn all' }}
      yarn_version: ${{ inputs.yarn_version || '3.6.3' }}

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write
